"""Security audit — каждый `/api/v1/*` endpoint должен иметь auth dependency.

Phase 5.x (2026-05-28). После каждого нового endpoint'а этот тест проверяет
что мы не забыли require_user / require_api_key. Если эта проверка не
пройдёт — это потенциальный auth bypass (anonymously доступный endpoint).

Регистрация исключений (publicly intentional): см. _PUBLIC_PREFIXES ниже.
"""

from __future__ import annotations

import re
from pathlib import Path

API_PATH = Path(__file__).parent.parent / "src" / "api.py"

# Endpoints которые ИНТЕНЦИОНАЛЬНО публичны (no auth):
_PUBLIC_PREFIXES = (
    "/health",
    "/metrics",
    "/auth/",
    "/openapi.json",
    "/docs",
    "/redoc",
)


def _extract_routes() -> list[tuple[str, str, str, str]]:
    """Парсит src/api.py и возвращает [(method, path, fname, full_decoration)]."""
    text = API_PATH.read_text()
    lines = text.split("\n")
    routes = []
    i = 0
    while i < len(lines):
        line = lines[i]
        # Match `@app.GET("/path", ...possibly other args)` — может быть multi-line
        m = re.match(r'@app\.(get|post|put|delete|patch)\("([^"]+)"', line)
        if not m:
            i += 1
            continue
        method, path = m.group(1), m.group(2)
        # Соберём весь декоратор (может быть multi-line с dependencies=[Depends(...)])
        decoration = line
        depth = decoration.count("(") - decoration.count(")")
        k = i
        while depth > 0 and k + 1 < len(lines):
            k += 1
            decoration += "\n" + lines[k]
            depth = decoration.count("(") - decoration.count(")")
        # Найдём def строку и signature
        for j in range(k + 1, min(k + 10, len(lines))):
            d = re.match(r"(?:async )?def (\w+)\(", lines[j])
            if d:
                fname = d.group(1)
                sig = lines[j]
                depth2 = sig.count("(") - sig.count(")")
                m2 = j
                while depth2 > 0 and m2 + 1 < len(lines):
                    m2 += 1
                    sig += "\n" + lines[m2]
                    depth2 = sig.count("(") - sig.count(")")
                routes.append((method, path, fname, decoration + sig))
                break
        i += 1
    return routes


def _has_auth_dependency(decoration_plus_sig: str) -> bool:
    """Любой из: require_user, require_api_key, dependencies=[Depends(...)].

    Также допускаем `verify_api_key` (legacy name).
    """
    auth_tokens = ("require_user", "require_api_key", "verify_api_key")
    return any(tok in decoration_plus_sig for tok in auth_tokens)


def test_all_api_routes_have_auth():
    """Любой `/api/v1/*` endpoint (включая dash и legacy) должен иметь auth.

    Если этот тест падает — кто-то добавил endpoint без auth dependency.
    Либо добавь require_user / require_api_key, либо если endpoint должен
    быть публичным — добавь его prefix в `_PUBLIC_PREFIXES` (с обоснованием).
    """
    routes = _extract_routes()
    assert len(routes) > 20, f"Expected 20+ routes, got {len(routes)} — parser broken?"

    unauth_routes = []
    for method, path, fname, body in routes:
        if path.startswith(_PUBLIC_PREFIXES):
            continue
        if not path.startswith("/api/v1/"):
            continue  # /openapi, /favicon и т.п. — не нашего scope
        if not _has_auth_dependency(body):
            unauth_routes.append(f"{method.upper()} {path} ({fname})")

    assert not unauth_routes, (
        "Found /api/v1/* routes without auth dependency:\n  "
        + "\n  ".join(unauth_routes)
        + "\nAdd require_user/require_api_key or whitelist in _PUBLIC_PREFIXES."
    )


def test_dash_routes_use_jwt_not_api_key():
    """`/api/v1/dash/*` должны идти через require_user (JWT cookie), не X-API-Key.

    X-API-Key для ERP / internal integrations. Dash — для frontend dashboard'а,
    Cookie auth — единственный валидный путь.
    """
    routes = _extract_routes()
    misrouted = []
    for method, path, fname, body in routes:
        if not path.startswith("/api/v1/dash/"):
            continue
        if "require_user" not in body:
            misrouted.append(f"{method.upper()} {path} ({fname})")
    assert not misrouted, "Dash routes without require_user (JWT auth):\n  " + "\n  ".join(
        misrouted
    )


def test_public_prefix_endpoints_actually_exist():
    """Sanity: всё в _PUBLIC_PREFIXES — реальные endpoint'ы (не stale strings)."""
    text = API_PATH.read_text()
    for prefix in _PUBLIC_PREFIXES:
        # Любой endpoint начинающийся с этого prefix должен быть в коде
        if prefix == "/auth/":
            assert '@app.post("/auth/' in text or '@app.get("/auth/' in text
        elif prefix == "/openapi.json":
            # auto-generated by FastAPI, не нужно проверять в коде
            continue
        elif prefix in ("/docs", "/redoc"):
            continue  # FastAPI built-in
        else:
            assert prefix in text, f"_PUBLIC_PREFIXES contains stale '{prefix}'"
